[project]
name = "repl-nix-mcqvision"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.1.3",
    "opencv-python-headless>=4.10.0.84",
    "pandas>=2.2.3",
    "plotly>=5.24.1",
    "streamlit>=1.40.2",
]
